# Generated by Django 2.0.7 on 2018-07-30 02:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_order_id', models.PositiveIntegerField(blank=True, null=True)),
                ('item_menu_name', models.CharField(max_length=64)),
                ('quantity', models.IntegerField()),
                ('item_price', models.FloatField()),
                ('status', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('menu_type', models.CharField(max_length=64)),
                ('menu_name', models.CharField(max_length=64)),
                ('menu_size', models.CharField(blank=True, max_length=64)),
                ('menu_price', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_date', models.DateTimeField()),
                ('status', models.CharField(max_length=64)),
                ('order_price', models.FloatField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PizzaTopping',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pizza_topping_name', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='SubTopping',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sub_topping_name', models.CharField(max_length=64)),
            ],
        ),
        migrations.AddField(
            model_name='item',
            name='topping_pizza',
            field=models.ManyToManyField(blank=True, related_name='topping_pizza', to='orders.PizzaTopping'),
        ),
        migrations.AddField(
            model_name='item',
            name='topping_sub',
            field=models.ManyToManyField(blank=True, related_name='topping_sub', to='orders.SubTopping'),
        ),
        migrations.AddField(
            model_name='item',
            name='username',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
